// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzkaukcjeunqxqpzsswc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6a2F1a2NqZXVucXhxcHpzc3djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1ODI2MjUsImV4cCI6MjA1MzE1ODYyNX0.TxCRzsdp9SrSW33eTwF9caWx8ZOVut_tAKjfZlGXAXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);